version: 0.1

phases:
  prebuild:
    commands:
      - npm install
      - npm test
  build:
    commands:
      - npm run webpack
artifacts:
  files:
    - index.html
    - favicon.ico
    - BLuekenResume.doc
    - styles/*
    - images/*
    - dist/bundle.js
